app: depoly-base
ssh_url: depoly-base@deploy.eu2.frbit.com
git_remote: depoly-base/master
before:
    code/up: {  }
after:
    code/down:
        - 'php craft migrate/all'
        - 'php craft project-config/apply'
