dateModified: 1722391868
email:
  fromEmail: jennifer@ambitious.co.nz
  fromName: newnew
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    471af014-4185-4a63-90e2-12c8a5e3154b: newnew # newnew
    67027eac-cd5e-41a7-a5e7-f3c249e6b63e: newnew # newnew
plugins:
  copy:
    edition: standard
    enabled: true
    schemaVersion: 1.0.0
system:
  edition: solo
  live: true
  name: newnew
  schemaVersion: 5.0.0.21
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  require2fa: false
  requireEmailVerification: true
